/*
          # Initial Schema Setup
          This migration sets up the core tables for the e-commerce application, including products, categories, user profiles, and orders. It also seeds the database with initial data.

          ## Query Description: This script is foundational and should be run on a new project. It creates the entire database structure. If run on an existing database with conflicting table names, it will fail. It is not reversible without a backup.
          
          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "High"
          - Requires-Backup: true
          - Reversible: false
          
          ## Structure Details:
          - Creates tables: `categories`, `products`, `profiles`, `orders`, `order_items`
          - Creates trigger: `on_auth_user_created` to populate `profiles` table.
          
          ## Security Implications:
          - RLS Status: Enabled for all new tables.
          - Policy Changes: Yes, new policies are created to secure user data.
          - Auth Requirements: Policies rely on `auth.uid()` for user identification.
          
          ## Performance Impact:
          - Indexes: Primary keys and foreign keys are indexed automatically.
          - Triggers: One trigger is added on `auth.users`.
          - Estimated Impact: Low on a new database.
          */

-- 1. CATEGORIES TABLE
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public categories are viewable by everyone." ON categories FOR SELECT USING (true);

-- 2. PRODUCTS TABLE
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price REAL NOT NULL,
    description TEXT,
    image TEXT,
    category_id BIGINT REFERENCES categories(id),
    rating JSONB DEFAULT '{"rate": 0, "count": 0}',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public products are viewable by everyone." ON products FOR SELECT USING (true);

-- 3. PROFILES TABLE
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    updated_at TIMESTAMPTZ
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile." ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Function and Trigger to create a profile for each new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name)
  VALUES (new.id, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 4. ORDERS TABLE
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    total_amount REAL NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    shipping_address JSONB
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own orders." ON orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own orders." ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. ORDER_ITEMS TABLE
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    quantity INT NOT NULL,
    price_at_purchase REAL NOT NULL
);
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view items in their own orders." ON order_items FOR SELECT USING (
    auth.uid() = (SELECT user_id FROM orders WHERE id = order_id)
);
CREATE POLICY "Users can insert items into their own new orders." ON order_items FOR INSERT WITH CHECK (
    auth.uid() = (SELECT user_id FROM orders WHERE id = order_id)
);


-- SEEDING DATA
-- Seed Categories
INSERT INTO categories (name) VALUES
('electronics'),
('jewelery'),
('men''s clothing'),
('women''s clothing'),
('books'),
('home'),
('sports'),
('toys');

-- Seed Products
INSERT INTO products (title, price, description, image, category_id, rating) VALUES
('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', (SELECT id from categories where name = 'men''s clothing'), '{"rate": 3.9, "count": 120}'),
('Mens Casual Premium Slim Fit T-Shirts ', 22.3, 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', (SELECT id from categories where name = 'men''s clothing'), '{"rate": 4.1, "count": 259}'),
('Mens Cotton Jacket', 55.99, 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', (SELECT id from categories where name = 'men''s clothing'), '{"rate": 4.7, "count": 500}'),
('John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 695, 'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', (SELECT id from categories where name = 'jewelery'), '{"rate": 4.6, "count": 400}'),
('Solid Gold Petite Micropave ', 168, 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', (SELECT id from categories where name = 'jewelery'), '{"rate": 3.9, "count": 70}'),
('WD 2TB Elements Portable External Hard Drive - USB 3.0 ', 64, 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', (SELECT id from categories where name = 'electronics'), '{"rate": 3.3, "count": 203}'),
('SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 109, 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 'https://fakestoreapi.com/img/61U7T1KfZwL._AC_SX679_.jpg', (SELECT id from categories where name = 'electronics'), '{"rate": 2.9, "count": 470}'),
('BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 56.99, 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed.', 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', (SELECT id from categories where name = 'women''s clothing'), '{"rate": 2.6, "count": 235}'),
('The Lord of the Rings', 25.99, 'The Fellowship of the Ring, part one of J.R.R. Tolkien''s epic masterpiece, first reached these shores on October 21, 1954, arriving, as C. S. Lewis proclaimed, "like a lightning from a clear sky."', 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?q=80&w=2112&auto=format&fit=crop', (SELECT id from categories where name = 'books'), '{"rate": 4.9, "count": 1500}'),
('Ergonomic Office Chair', 149.99, 'This ergonomic office chair provides comprehensive support for your back and neck, with a comfortable headrest and adjustable lumbar support. The breathable mesh material keeps you cool throughout the day.', 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?q=80&w=1974&auto=format&fit=crop', (SELECT id from categories where name = 'home'), '{"rate": 4.5, "count": 350}'),
('Professional Football', 29.99, 'Official size and weight professional football, designed for optimal performance and durability. Perfect for training and competitive matches.', 'https://images.unsplash.com/photo-1543351368-350350a86f78?q=80&w=1974&auto=format&fit=crop', (SELECT id from categories where name = 'sports'), '{"rate": 4.8, "count": 800}'),
('Wooden Building Blocks Set', 39.99, 'A classic set of 100 wooden building blocks in various shapes and colors. Encourages creativity, fine motor skills, and imaginative play for children.', 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=2070&auto=format&fit=crop', (SELECT id from categories where name = 'toys'), '{"rate": 4.7, "count": 450}');
</sql>
